baseURL = "/"
locale = "en-us"
title = "Notes"
theme = "book"
relativeURLs = true

[params]
  BookSection = "*"
  BookSearch = true
  BookToC = true
  BookTheme = "auto"

[markup.highlight]
  style = "one-dark"
  lineNos = false
  noClasses = false
  guessSyntax = true

[markup.goldmark.renderer]
  unsafe = true
