baseURL = "https://aloktripathi1.github.io/tds-notes/"
languageCode = "en-us"
title = "TDS Notes"
theme = "book"

[params]
  BookSection = "docs"
  BookSearch = true
  BookToC = true
  BookTheme = "auto"

[markup.highlight]
  style = "dracula"

[markup.goldmark.renderer]
  unsafe = true
